jwt:
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  issuer: valilechek
  expiration: 60
  token:
    password:
      encoder:
        secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
        iteration: 33
        keylength: 256

server:
  port: 8083

spring:
  r2dbc:
#    url: r2dbc:pool:postgres://localhost:3309/data-provider?createDatabaseIfNotExist=true
    url: r2dbc:postgres://localhost:5433/data-provider
    username: data-provider
    password: data-provider
  liquibase:
    enabled: on
    url: jdbc:postgresql://localhost:5433/data-provider
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
#    change-log: classpath:/db/changelog/db.changelog-master.yml