jwt:
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  issuer: valilechek
  expiration: 60
  token:
    password:
      encoder:
        secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
        iteration: 33
        keylength: 256

data-provider:
  api-key: PZiVNWZs13oR9WlO5pm6HLfdajkEaq4d


server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:postgres://localhost:5433/data-provider
    username: data-provider
    password: data-provider
    properties:
      schema: data_provider
  liquibase:
    enabled: on
    url: jdbc:postgresql://localhost:5433/data-provider
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    default-schema: ${spring.r2dbc.properties.schema}
    change-log: db/changelog/db.changelog-master.yaml
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 600s

logging:
  level:
    root: TRACE
    org.springframework.boot.autoconfigure.security: TRACE
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.data: DEBUG
    io.r2dbc.postgresql: DEBUG

cache:
  enabled: true

scheduling:
  enabled: true