#!/usr/bin/env bash
ORIGINAL_DIR=$(pwd)
echo $ORIGINAL_DIR

cd ../ && docker-compose up --detach data-provider
trap cd_to_original_location EXIT

function cd_to_original_location()
{
    cd $ORIGINAL_DIR
}