version: '3.9'

services:
  data-provider:
    mem_limit: 512m
    cpus: 0.5
    platform: linux/amd64
    image: data-provider-db:latest
    command: postgres -c 'max_connections=10000'
    container_name: data-provider-postgres
    ports:
      - "5433:5432"
    environment:
      - "DEBUG=true"
      - "POSTGRES_PASSWORD=postgres"
      - "PG_TRUST_LOCALNET=true"
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres && psql -lqt -U postgres | grep -qw healtcheck_db"]
          interval: 5s
          timeout: 5s
          retries: 50
    volumes:
      - ./docker-postgres/data-ms:/var/lib/postgresql/data